config/routes.rb
Rails.application.routes.draw do
    resources :books do
        delete 'destroy_all', on: :collection
    post "/books/:id" => "books#update"
        resources :comments, only: [:new, :create, :destroy]
    end
    
    resources :comments, only: [:destroy]

    get "/signup" => "users#new"
    post "/signup" =>"users#create"
    get "signin" => "session#new"
    post "signin" => "session#create"
    get "signout" => "session#destroy"
    get "users/edit" => "users#edit", as: "edit_user"
    patch "users/" => "users#update" , as: "user"
    get "users/:id/show" => "users#show", as: "show_user"
    
    post '/guest_login', to: 'sessions#guest_login'

    root to: "homes#top"
    get 'homes/about'

    # get "/books" => "books#index"
    # post "/books" => "books#create"
    # get "/books/new" => "books#new" , as:"new_book"
    # get "/books/:id/edit" => "books#edit" , as:"edit_book"
    # get "/books/:id" => "books#show" , as:"book"

    # ニックネームを書いていないですが書いていない場合は、すぐ上のニックネーム(book)を引き継ぎます。
    # showと同じニックネーム・URLパターンになってしまいますが、HTTPメソッドが異なるのでちゃんと区別されます。
    # delete "/books/:id" => "books#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true
  has_many :comments
  

  validates :year ,presence: true
  validates :month ,presence: true
  validates :inout ,presence: true
  validates :category ,presence: true
  validates :amount ,presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :books
  has_many :comments
  
  has_many_attached :avatar
  
  validates :name,presence: true, length: {maximum: 20}
  validates :email,presence: true,uniqueness: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    @current_user ||= User.find_by(email: 'guest@example.com') if Rails.env.development?
    # ゲストユーザーが存在しない場合は、デフォルトでid=1のユーザーをゲストユーザーとして扱う
    @current_user ||= User.find(1) if Rails.env.development?
  end

  def logged_in?
    !!current_user
  end

  def redirect_to_signin
    unless logged_in? || guest_user?
      redirect_to signin_path
    end
  end

  def guest_user?
    current_user.email == 'guest@example.com'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :redirect_to_signin

  def index
    @books = Book.where(user_id: session[:user_id])
    # allだったのを、ログインしているユーザーのidで検索するようにしています。
    @books = @books.where(year: params.require(:year)) if params[:year].present?
    @books = @books.where(month: params.require(:month)) if params[:month].present?
    @books = @books.where(inout: params.require(:inout)) if params[:inout].present?
    @comments = Comment.where(book_id: @books.pluck(:id))
  end

  def show
    @book = Book.where(user_id: session[:user_id]).find(params[:id])
    @comments = @book.comments
  end

  def new
    @book = Book.new
    # @book.year = 2019
    # で直接フォームに入力している状態にできる
  end

  def create
    @book = current_user.books.build(book_params)
    @book = Book.new(book_params)
    @book.user_id = session[:user_id]
    # 現在ログインしているユーザーのid {session[:user_id]} を@book.user_idに代入することで、誰が家計簿を登録したかを記録することができます。
    # もし@book.user_id = session[:user_id]がない場合、user_idカラムには何も値が代入されず、
    # ログインしているユーザーの情報が家計簿に保存されないため、誰が登録したのかが分からなくなってしまいます。
    if @book.save
      flash[:notice] = "家計簿に「#{@book.year}年#{@book.month}月#{@book.category}」を投稿しました"
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.where(user_id: session[:user_id]).find(params[:id])
  end

  def update
    @book = Book.where(user_id: session[:user_id]).find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="家計簿の「#{@book.year}年#{@book.month}月#{@book.category}」を更新しました"
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.where(user_id: session[:user_id]).find(params[:id])
    @book.destroy
    flash[:notice] = "削除しました"
    redirect_to books_path
  end
  
  def destroy_all
    @books = Book.where(user_id: session[:user_id])
    @books.destroy_all
    redirect_to request.referer
  end

  private
  
  def book_params
    params.require(:book).permit(:year,:month, :inout, :amount, :category)
  end
  

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @book = Book.find(params[:book_id])
    @comment = Comment.new
  end
  
  def create
    book = Book.find(params[:book_id]) 
    comment = current_user.comments.new(comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_to book_path(book), notice: 'コメントを投稿しました。'
    else
      flash.now[:alert] = 'コメントの投稿に失敗しました。'
      render 'books/index'
    end
  end
  
  def destroy
    comment = Comment.find(params[:id])
    book = comment.book
    comment.destroy
    redirect_to book_path(book), notice: 'コメントを削除しました。'
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :redirect_to_books, only: [:new, :create]

  def guest_login
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = 'password'
      user.name = 'Guest'
    end
    log_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  
  def new
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      flash[:notice] = "ログインに成功しました"
      session[:user_id] = user.id
      redirect_to books_path
    else
      flash[:alert] = "ログインに失敗しました"
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to signin_path
    
  end
  
  private
  
  def redirect_to_books
    redirect_to books_path if session[:user_id].present?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_signin, only: [:show, :edit, :update]
  
    def self.guest
      find_or_create_by!(email: 'guest@example.com') do |user|
        user.name = 'Guest User'
        user.password = SecureRandom.urlsafe_base64
      end
    end
  
  def show
    @user = User.find(params[:id])
    if session[:user_id] == @user.id
      # プロフィールページにアクセスしているユーザーが、表示しているユーザー自身である場合
      @books = @user.books
    else
      # プロフィールページにアクセスしているユーザーが、表示しているユーザー自身ではない場合
      render 'session/new'
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "会員登録が完了しました"
      redirect_to signin_path
    else
      flash[:alert] ="会員登録に失敗しました"
      render :new
    end
  end
  
  def edit
    @user = User.find(session[:user_id])
  end
  
  def update
    @user = User.find(session[:user_id])
    if @user.update(user_params1)
      if params[:user][:avatar].present?
        @user.create_avatar(params[:user][:avatar])
      end
      flash[:notice] = "会員登録の内容を更新しました"
      redirect_to edit_user_path(@user)
    else
      flash[:alert] = "更新が失敗しました"
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def user_params1
    params.require(:user).permit(:name, :email, :avatar)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h3>家計簿<%= type %></h3>
<%= form_with model:book , local: true do |f| %>
　　　　　　　　<!--model:bookの model :bookはだめ>
  <!-- form_withの引数としては、まずBookモデルのインスタンス@bookがあります。
  @bookをmodelというキーでform_withへ渡しています。ここへモデルを渡すために、
  コントローラのnewメソッド内で空っぽのインスタンス変数(Book.new)を準備しています -->
  
  <!-- もう一つ渡しているlocalオプションですが、これをtrueに設定しないとうまく動作しないことがあります。
       この設定で非同期通信という機能をオフにしているのですが、少し応用的な内容になってくるので、
         ここでは詳しくは解説しません。興味のある方は、非同期通信が何か調べてみてください。-->
  
    <% if book.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= book.errors.count %>つのエラーが発生しました</h2>
        <ul style="list-style: none;" >
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-group">
    <label>年度</label>
    <%= f.number_field :year, class:"form-control" %>
  </div>
  <div class="form-group">
    <label>月</label>
    <%= f.number_field :month, class:"form-control" %>
  </div>
  <div class="form-group">
    <label>区分</label>
    <%= f.select :inout,[["収入",1],["支出",2]],{}, class:"form-control" %>
  </div>
  <div class="form-group">
    <label>科目</label>
    <%= f.text_field :category, class:"form-control" %>
  </div>
  <div class="form-group">
    <label>金額</label>
    <%= f.number_field :amount, class:"form-control" %>
  </div>
  
  <%= f.submit type2, class:"btn btn-primary mt-2" %>
  <%= link_to "戻る" , books_path , class:"btn btn-secondary mt-2"  %>
<% end %>

app/views/books/_search.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with method:"get" , local: true do |f| %>
      <div class="row">
        <div class="col">
          <%= f.number_field "year" , placeholder: "年度を入力" , class:"form-control" %>
        </div>
        <div class="col">
          <%= f.number_field "month" , placeholder: "対象月を入力" , class:"form-control" %>
        </div>
        <div class="col">
          <%= f.select "inout", [["収入", 1], ["支出", 2]], {}, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.submit "検索", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<%= render partial: "form", locals: {type:"を変更しよう",type2:"変更する" ,book: @book,method: "patch"} %>

app/views/books/index.html.erb
<%= render "search" %>

<table class="table table-striped">
  <tr>
    <th>年月</th>
    <th>区分</th>
    <th>科目</th>
    <th>金額</th>
    <th>リンク先
      <span id="all-delete" >
        <%= link_to "一括削除", destroy_all_books_path, method: :delete, data: { confirm: "全てを削除しますか？" }, class: "btn btn-danger" %>
      </span>
    </th>
  </tr>

  <% sum = 0 %>
  <% income = 0 %>
  <% expense = 0 %>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.year %>年<%= book.month %>月</td>
    <td class="<%= book.inout == 1 ? 'text-success' : 'text-danger' %>">
      <%= book.inout == 1 ? '収入' : '支出' %>
    </td>
    <td><%= book.category %></td>
    <td><%= book.amount %>万円</td>
    <td>
      <%= link_to "詳細", book_path(book) , class:"btn btn-info" %>
     <!-- (book)は@books.each do |book|のインスタン変数のbookのこと -->
      <%= link_to "変更", edit_book_path(book), class:"btn btn-warning" %>
      <%= link_to "削除", book_path(book) ,method: "delete",data: {confirm:'本当に消すの？' }, class:"btn btn-danger" %>
       <!-- 注意するのは、link_toの中でmethodを指定している部分です。これを忘れてしまうと、ただの詳細画面へのリンクになってしまいます
            '本当に消すの'の部分は、" " ではNG！　必ず' 'で囲うこと！-->
      <%= link_to "コメントする",new_book_comment_path(book) , class:"btn btn-success"  %>
    </td>
  </tr>
    <% if book.inout == 1 %>
      <% sum = sum + book.amount %>
    <% else %>
      <% sum = sum - book.amount %>
    <% end %>

    <% if book.inout == 1 %>
      <% income = income + book.amount %>
    <% end %>

    <% if book.inout == 2 %>
      <% expense  += book.amount %>
    <% end %>

  <% end %>
  <tr>
    <td><strong>収入の合計</strong></td>
    <td><strong><%= income %>万円</strong></td>
    <td><strong>支出の合計</strong></td>
    <td><strong><%= expense %>万円</strong></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td><strong>合計</strong></td>
    <td><strong><%= sum %>万円</strong></td>
    <td></td>
  </tr>
</table>
<%= link_to "新規投稿" , new_book_path , class:"btn btn-success" %>

app/views/books/new.html.erb
<%= render partial: "form", locals: {type:"を新規登録しよう",type2:"新規登録",book: @book,method: nil} %>

app/views/books/show.html.erb
<h3>家計簿の詳細をみよう</h3>
<table class="table table-striped">
  <tr>
    <th>年月</th>
    <td><%= @book.year%>年<%= @book.month %>月</td>
  </tr>
  <tr>
    <th>区分</th>
    <td>
      <% if @book.inout == 1 %>
        収入
      <% else @book.inout == 2 %>
        支出
      <% end %>
    </td>
  </tr>
  <tr>
    <th>科目</th>
    <td><%= @book.category %></td>
  </tr>
  <tr>
    <th>金額</th>
    <td><%= @book.amount %>万円</td>
  </tr>
  <tr>
    <th>コメント</th>
    <td>
      <% @book.comments.each do |comment| %>
        <p>
          <%= comment.comment %>
          <span class="text-end">
            <%= link_to '削除', comment, method: :delete, data: { confirm: '本当に削除しますか？' },class:"btn btn-danger" %>
          </span>
        </p>
      <% end %>
    </td>
  </tr>
</table>
<%= link_to "戻る",books_path,class:"btn btn-secondary"%>

app/views/comments/new.html.erb
<h3>家計簿にコメントしてみよう</h3>
<table class="table table-striped">
  <tr>
    <th>年月</th>
    <td><%= @book.year%>年<%= @book.month %>月</td>
  </tr>
  <tr>
    <th>区分</th>
    <td>
      <% if @book.inout == 1 %>
        収入
      <% else @book.inout == 2 %>
        支出
      <% end %>
    </td>
  </tr>
  <tr>
    <th>科目</th>
    <td><%= @book.category %></td>
  </tr>
  <tr>
    <th>金額</th>
    <td><%= @book.amount %>万円</td>
  </tr>
  <tr>
    <th>コメント</th>
    <td>
      <%= form_with model: @comment, url: book_comments_path(@book), local: true do |f| %>
        <p><%= f.text_area :comment, placeholder: "コメントを入力してください" , style:"width: 700px" %></p>
        <p><%= f.submit "コメントする", class: "btn btn-primary" %></p>
      <% end %>
    </td>
  </tr>
</table>
<%= link_to "戻る", books_path, class: "btn btn-secondary" %>

app/views/homes/about.html.erb
<div class="map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37221.48611891392!2d139.81772617043444!3d35.7007903004807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188ed0d12f9adf%3A0x7d1d4fb31f43f72a!2z5p2x5Lqs44K544Kr44Kk44OE44Oq44O8!5e0!3m2!1sja!2sjp!4v1685340691858!5m2!1sja!2sjp" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

app/views/homes/top.html.erb
<div class="row">
  <div class="col text-center">
    <h1 class="title">ようこそ！　家計簿アプリへ！</h1>
    <h3>はじめるには、上記から会員登録もしくはログインをお願います。</h3>
    <h3>もしくは、ゲストでログインすることも可能です。</h3>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>家計簿アプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
　　<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <%= link_to root_path , id:"title" do %>
        <h3>家計簿アプリ</h3>
      <% end %>
      <div>
        <% if session[:user_id].present? %>
          <%= link_to "会員情報の確認", show_user_path(session[:user_id]) , class:"btn btn-outline-secondary" %>
          <%= link_to "会員情報の更新", edit_user_path , class:"btn btn-outline-secondary" %>
          <%= link_to "ログアウト", signout_path , class:"btn btn-outline-danger" %>
        <% else %>
          <%= link_to"会員登録",signup_path, class:"btn btn-outline-success" %>
          <%= link_to"ログイン",signin_path, class:"btn btn-outline-primary" %>
          <%= link_to"About", homes_about_path, class:"btn btn-outline-secondary" %>
        <% end %>
      </div>
    </nav>
    <div id="body-main">
      <div class="container" >
        <% if flash[:notice] %>
          <div class="alert alert-success" role="alert" >
            <%= flash[:notice] %>
          </div>
        <% end %>
  
        <% if flash[:alert] %>
          <div class="alert alert-danger" role="alert" >
            <%= flash[:alert] %>
          </div>
        <% end %>
  
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<h1 class="mb-3" >ログイン</h1>
<%= form_with url: signin_path, local: true do |f| %>
 <div class="form-group">

  <div class="form-group">
   <label>メールアドレス</label>
   <%= f.text_field :email, class:"form-control" %>
 </div>
 <div class="form-group">
   <label>パスワード</label>
   <%= f.password_field :password, class:"form-control" %>
 </div>
 
 <%= f.submit "ログイン", class:"btn btn-primary mt-2" %>
 
<% end %>

<div class="row justify-content-center">
  <div class="col-md-6 text-center">
    <%= link_to "ゲストとしてログインする", books_path, class: "btn btn-outline-secondary btn-block my-5", style: "width: 500px;" %>
  </div>
</div>

app/views/users/edit.html.erb
<h3>会員登録の情報を変更しよう</h3>
<p>※パスワードは変更できません</p>

<%= form_with model: @user, url: user_path(@user), method: "patch", local: true do |f| %>

  <div class="form-group">
    <label>名前</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>メールアドレス</label>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <%= f.submit "変更する", class: "btn btn-primary mt-2" %>
<% end %>

app/views/users/new.html.erb
<h1>会員登録</h1>
<%= form_with model: @user , url: signup_path, local: true do |f| %>
 <div class="form-group">
   <label>名前</label>
   <%= f.text_field :name, class:"form-control" %>
 </div>
  <div class="form-group">
   <label>メールアドレス</label>
   <%= f.text_field :email, class:"form-control" %>
 </div>
 <div class="form-group">
   <label>パスワード</label>
   <%= f.password_field :password, class:"form-control" %>
 </div>
  <div class="form-group">
   <label>パスワード確認用</label>
   <%= f.password_field :password_confirmation, class:"form-control" %>
 </div>

 <%= f.submit "会員登録", class:"btn btn-success mt-2" %>

<% end %>

<div class="row justify-content-center">
  <div class="col-md-6 text-center">
    <%= link_to "ゲストとしてログインする", books_path, class: "btn btn-outline-secondary btn-block my-5", style: "width: 500px;" %>
  </div>
</div>

app/views/users/show.html.erb
<h3>会員情報をみよう</h3>
<table class="table table-striped">
  <tr>
    <th style="width: 500px;" >名前</th>
    <th><%= @user.name %></th>
  </tr>
  <tr>
    <th style="width: 500px;" >メールアドレス</th>
    <th><%= @user.email %></th>
  </tr>
</table>

<%= link_to "戻る",books_path,class:"btn btn-secondary"%>